### ISSUE TITLE
Not an issue but no other way of asking this

### ISSUE THREAD

**Issue by L0rDPSYCH0** [andreyviktorov/notiny#7]
Hi, 
I absolutely love your plugin. Quick question though, since my frontend skills are fairly limited. 
I want to use your plugin in a dialog, but there is a change I might have 10+ notifications that will not hide by default, only on click . Is there a way to show for example 5 of them and to see the rest you would have to scroll inside a container?

**Comment by 4ndv** [comment]
Hi! You may try this:

```css
.notiny-container {
  max-height: 300px;
  overflow-y: scroll;
  overflow-x: hidden;
}
```
